trigger:
- main

pool:
  name: self-vm   # your self-hosted agent

steps:
- script: |
    echo "Checking Python..."
    python3 --version
  displayName: Check Python

- script: |
    echo "Installing dependencies..."
    pip3 install --upgrade pip
    pip3 install -r requirements.txt
  displayName: Install dependencies

- script: |
    echo "Running application..."
    python3 app.py
  displayName: Run app
  env:
    GOOGLE_API_KEY: $(GOOGLE_API_KEY)

    - task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
