trigger:
- main

pool:
  name: self-vm

steps:
- script: |
    echo Checking Python version...
    python3 --version
  displayName: Check Python

- script: |
    echo Installing dependencies...
    pip3 install --upgrade pip
    pip3 install -r requirements.txt
  displayName: Install dependencies

- script: |
    echo Running tests...
    pip3 install pytest pytest-azurepipelines
    pytest || echo No tests found
  displayName: Run tests

- task: CopyFiles@2
  displayName: Copy files
  inputs:
    SourceFolder: $(System.DefaultWorkingDirectory)
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: Container
